{"time":"2025-06-24T09:58:22.7790673-04:00","level":"INFO","msg":"stream: starting","core version":"0.20.1","symlink path":"c:\\Users\\LiamMurphy(DMC)\\Documents\\Weave\\eval\\wandb\\run-20250624_095822-mqrerlhg\\logs\\debug-core.log"}
{"time":"2025-06-24T09:58:24.6425869-04:00","level":"INFO","msg":"stream: created new stream","id":"mqrerlhg"}
{"time":"2025-06-24T09:58:24.6425869-04:00","level":"INFO","msg":"stream: started","id":"mqrerlhg"}
{"time":"2025-06-24T09:58:24.6425869-04:00","level":"INFO","msg":"handler: started","stream_id":"mqrerlhg"}
{"time":"2025-06-24T09:58:24.6425869-04:00","level":"INFO","msg":"sender: started","stream_id":"mqrerlhg"}
{"time":"2025-06-24T09:58:24.6425869-04:00","level":"INFO","msg":"writer: Do: started","stream_id":"mqrerlhg"}
{"time":"2025-06-24T09:58:24.7473005-04:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-06-24T09:58:25.8408785-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"createRunFiles\"]}],\"data\":{\"createRunFiles\":null}}"}
{"time":"2025-06-24T09:58:25.9151366-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"project\",\"run\"]}],\"data\":{\"project\":{\"run\":null}}}"}
{"time":"2025-06-24T09:58:28.5653638-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"project\"]}],\"data\":{\"project\":null}}"}
{"time":"2025-06-24T09:58:32.820763-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"createRunFiles\"]}],\"data\":{\"createRunFiles\":null}}"}
{"time":"2025-06-24T09:58:35.3362136-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"project\"]}],\"data\":{\"project\":null}}"}
{"time":"2025-06-24T09:58:39.3584464-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/graphql","body":"{\"errors\":[{\"message\":\"dial tcp 10.101.166.169:3306: connect: connection refused\",\"path\":[\"createRunFiles\"]}],\"data\":{\"createRunFiles\":null}}"}
{"time":"2025-06-24T09:58:45.0054495-04:00","level":"INFO","msg":"api: retrying HTTP error","status":500,"url":"https://weave.assessmentforgood.cloud/files/liammurphy7657/llamaguard_classification/mqrerlhg/file_stream","body":"{\"error\":\"context deadline exceeded\"}"}
